### ISSUE TITLE
You abandoned the project ??? ..

### ISSUE THREAD

**Issue by hymsoft** [thevuong/v-bootstrap4#3]
Hello, greetings from Argentina

You have not updated your project for 11 months. Do you have it abandoned ??? Classes like **"d-flex" - "align-self-start"** and others are not supported ...

**Comment by thevuong** [comment]
hymsoft,
Yes, the last 11 months I have not had any updates while bootstrap has released v4.0.0 beta.2. Now the v bootstrap4 package has been updated to the latest bootstrap.
Best,
Vuong

**Comment by hymsoft** [comment]
Thanks for answering. Waiting for news. Greetings from Argentina

Hugo A. Segura
HyM soft
Rio Gallegos – Patagonia Argentina

Enviado desde Correo para Windows 10

De: Vuong Phan
Enviado: sábado, 21 de octubre de 2017 14:46
Para: thevuong/v-bootstrap4
CC: Hugo Antonio Segura; Author
Asunto: Re: [thevuong/v-bootstrap4] You abandoned the project ??? .. (#3)

hymsoft,
Yes, the last 11 months I have not had any updates while bootstrap has released v4.0.0 beta.2. Now the v bootstrap4 package has been updated to the latest bootstrap.
Best,
Vuong
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus
